version: "3.5"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: clean
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
        
  spring-boot-app:
    image: cleancqrs:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/clean
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
    ports:
      - "8080:8080"
    depends_on: 
      - mysql
  
  
volumes:
  mysql-data: